global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # ------------------- Node Exporter -------------------
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['host.docker.internal:9100', 'localhost:9100']

  # ------------------- cAdvisor -------------------
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
