global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # ------------------- Node Exporter -------------------
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  # ------------------- cAdvisor -------------------
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # ------------------- Docker daemons (opcional) -------------------
  # Si quieres monitorear los contenedores Docker directamente
  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:9323']